//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ling.Audit.SourceGenerators.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ling.Audit.SourceGenerators.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All audit interfaces implemented by a type must use the same key type parameter..
        /// </summary>
        internal static string AuditKeyTypeMismatch_Description {
            get {
                return ResourceManager.GetString("AuditKeyTypeMismatch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; has multiple key types in audit interfaces: {1}.
        /// </summary>
        internal static string AuditKeyTypeMismatch_Message {
            get {
                return ResourceManager.GetString("AuditKeyTypeMismatch_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent audit key types.
        /// </summary>
        internal static string AuditKeyTypeMismatch_Title {
            get {
                return ResourceManager.GetString("AuditKeyTypeMismatch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit properties can only be generated for classes and records. Structs and record structs are not supported..
        /// </summary>
        internal static string AuditNotSupportedForValueType_Description {
            get {
                return ResourceManager.GetString("AuditNotSupportedForValueType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is a value type and cannot be audited.
        /// </summary>
        internal static string AuditNotSupportedForValueType_Message {
            get {
                return ResourceManager.GetString("AuditNotSupportedForValueType_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit not supported for value types.
        /// </summary>
        internal static string AuditNotSupportedForValueType_Title {
            get {
                return ResourceManager.GetString("AuditNotSupportedForValueType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types implementing audit interfaces must be declared as partial to support source generation of audit properties..
        /// </summary>
        internal static string AuditRequiresPartialType_Description {
            get {
                return ResourceManager.GetString("AuditRequiresPartialType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must be declared as partial to support auditing.
        /// </summary>
        internal static string AuditRequiresPartialType_Message {
            get {
                return ResourceManager.GetString("AuditRequiresPartialType_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit requires partial type.
        /// </summary>
        internal static string AuditRequiresPartialType_Title {
            get {
                return ResourceManager.GetString("AuditRequiresPartialType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using ICreationAudited interface instead.
        /// </summary>
        internal static string UseCreationAudited_Message {
            get {
                return ResourceManager.GetString("UseCreationAudited_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ICreationAudited interface.
        /// </summary>
        internal static string UseCreationAudited_Title {
            get {
                return ResourceManager.GetString("UseCreationAudited_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using IDeletionAudited interface instead.
        /// </summary>
        internal static string UseDeletionAudited_Message {
            get {
                return ResourceManager.GetString("UseDeletionAudited_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use IDeletionAudited interface.
        /// </summary>
        internal static string UseDeletionAudited_Title {
            get {
                return ResourceManager.GetString("UseDeletionAudited_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using IFullAudited interface instead.
        /// </summary>
        internal static string UseFullAudited_Message {
            get {
                return ResourceManager.GetString("UseFullAudited_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use IFullAudited interface.
        /// </summary>
        internal static string UseFullAudited_Title {
            get {
                return ResourceManager.GetString("UseFullAudited_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider using IModificationAudited interface instead.
        /// </summary>
        internal static string UseModificationAudited_Message {
            get {
                return ResourceManager.GetString("UseModificationAudited_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use IModificationAudited interface.
        /// </summary>
        internal static string UseModificationAudited_Title {
            get {
                return ResourceManager.GetString("UseModificationAudited_Title", resourceCulture);
            }
        }
    }
}
