using Ling.Audit.SourceGenerators.Helpers;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Ling.Audit.SourceGenerators;

partial class AuditPropertyGenerator
{
    private static string GetGeneratedCode(ClassDeclarationSyntax classDeclaration, List<AuditPropertyInfo> properties)
    {
        var (namespaceName, containingTypes) = GetTypeContext(classDeclaration);

        var cb = new CodeBuilder();

        cb.AppendLine("""
            // <auto-generated/>

            #pragma warning disable
            #nullable enable annotations

            """);

        cb.AppendLine($"namespace {namespaceName}")
            .OpenBrace();

        foreach (var type in containingTypes)
        {
            cb.AppendFormatLine("partial {0} {1}", type.Keyword, type.Name)
                .OpenBrace();
        }

        var classIdentifierWithInheritance = classDeclaration.Identifier.Text + GetInheritanceString(properties);

        cb.AppendFormatLine("[global::System.CodeDom.Compiler.GeneratedCode(\"Ling.Audit.SourceGenerators\", \"{0}\")]", AuditDefaults.Version)
            .AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]")
            .AppendFormatLine("partial class {0}", classIdentifierWithInheritance)
            .OpenBrace();

        var index = 0;
        foreach (var property in properties)
        {
            var inheritDocClass = property.PropertyName switch
            {
                AuditDefaults.CreatedBy => AuditDefaults.IHasCreatorTypeFullQualifiedMetadataName.Replace("Creator`1", "CreationUser{TKey}"),
                AuditDefaults.CreatedAt => AuditDefaults.IHasCreationTimeTypeFullQualifiedMetadataName,
                AuditDefaults.ModifiedBy => AuditDefaults.IHasModifierTypeFullQualifiedMetadataName.Replace("Modifier`1", "ModificationUser{TKey}"),
                AuditDefaults.ModifiedAt => AuditDefaults.IHasModificationTimeTypeFullQualifiedMetadataName,
                AuditDefaults.IsDeleted => AuditDefaults.ISoftDeleteTypeFullQualifiedMetadataName,
                AuditDefaults.DeletedBy => AuditDefaults.IHasDeleterTypeFullQualifiedMetadataName.Replace("Deleter`1", "DeletionUser{TKey}"),
                AuditDefaults.DeletedAt => AuditDefaults.IHasDeletionTimeTypeFullQualifiedMetadataName,
                _ => string.Empty,
            };

            cb.AppendFormatLine("/// <inheritdoc cref=\"global::{0}.{1}\"/>", inheritDocClass, property.PropertyName)
                .AppendFormatLine("public virtual {0} {1} {{ get; set; }}", property.PropertyType, property.PropertyName);

            if (++index < properties.Count)
            {
                cb.AppendLine();
            }
        }

        cb.CloseAllBrace();

        return cb.ToString();
    }

    private record TypeInfo(string Keyword, string Name);

    private static (string Namespace, List<TypeInfo> ContainingTypes) GetTypeContext(ClassDeclarationSyntax classDeclaration)
    {
        var types = new List<TypeInfo>();
        var parent = classDeclaration.Parent;
        var namespaceName = "global::System";

        while (parent != null)
        {
            switch (parent)
            {
                case ClassDeclarationSyntax classDecl:
                    types.Insert(0, new TypeInfo("class", classDecl.Identifier.Text));
                    break;

                case StructDeclarationSyntax structDecl:
                    types.Insert(0, new TypeInfo("struct", structDecl.Identifier.Text));
                    break;

                case RecordDeclarationSyntax recordDecl:
                    types.Insert(0, new TypeInfo("record", recordDecl.Identifier.Text));
                    break;

                case BaseNamespaceDeclarationSyntax namespaceDecl:
                    namespaceName = namespaceDecl.Name.ToString();
                    break;
            }

            parent = parent.Parent;
        }

        return (namespaceName, types);
    }

    private static string GetInheritanceString(List<AuditPropertyInfo> properties)
    {
        var inheritanceTypes = new[]
        {
            (PropertyName: AuditDefaults.CreatedBy, InterfaceName: AuditDefaults.IHasCreatorTypeFullQualifiedMetadataName),
            (PropertyName: AuditDefaults.ModifiedBy, InterfaceName: AuditDefaults.IHasModifierTypeFullQualifiedMetadataName),
            (PropertyName: AuditDefaults.DeletedBy, InterfaceName: AuditDefaults.IHasDeleterTypeFullQualifiedMetadataName)
        };

        var interfaces = inheritanceTypes
            .Select(t => properties.FirstOrDefault(p => p.PropertyName == t.PropertyName))
            .Where(p => p != null)
            .Select(p => "global::" + p.InterfaceName.Replace("`1", $"<{p.PropertyType}>"));

        return interfaces.Any()
            ? " : " + string.Join(", ", interfaces)
            : string.Empty;
    }
}
