name: Pull Request

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: ./.github/actions/setup-dotnet

    - name: Run tests
      run: dotnet test --configuration Release 
